name: Build multi-arch (amd64/arm64) docker image using AWS spot instances

on:
  workflow_call:
    inputs:
      DOCKER_IMAGE_NAME:
        type: string
        required: false
        default: ${{ github.repository }}
      DOCKER_IMAGE_TAG:
        type: string
        required: false
        default: latest
      REPOSITORY_URL:
        type: string
        required: false
        default: https://github.com/${{ github.repository }}.git
      CHECKOUT:
        type: string
        required: false
        default: ${{ github.sha }}
      WORKFLOW_REPOSITORY:
        type: string
        required: false
        default: pldin601/common-workflows
      WORKFLOW_CHECKOUT:
        type: string
        required: false
        default: v1.0.0
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

concurrency:
  cancel-in-progress: false
  group: build-multiarch-on-aws-spots

env:
  TERRAFORM_DIR: terraform/build-multiarch-on-aws-spots

jobs:
  spawn-spots:
    name: Spawn spot machines
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_docker_login: ${{ secrets.DOCKERHUB_USERNAME }}
      TF_VAR_docker_password: ${{ secrets.DOCKERHUB_TOKEN }}
      TF_VAR_aws_ec2_key_pair_name: ${{ github.repository }}@${{ github.sha }}
    outputs:
      PUBLIC_IPS: ${{ env.PUBLIC_IPS }}
      PRIVATE_KEY: ${{ env.PRIVATE_KEY }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@master
        with:
          repository: ${{ inputs.WORKFLOW_REPOSITORY }}
          ref: ${{ inputs.WORKFLOW_CHECKOUT }}
      -
        name: "Terraform: Setup"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.5
          terraform_wrapper: false
      -
        name: "Terraform: Init"
        run: terraform -chdir=$TERRAFORM_DIR init
      -
        name: "Terraform: Apply"
        run: terraform -chdir=$TERRAFORM_DIR apply -auto-approve
      -
        name: "Save Terraform State File"
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: terraform-state
          path: ${{ env.TERRAFORM_DIR }}/terraform.tfstate
          retention-days: 1
      -
        id: outputs
        name: "Terraform: Parse Outputs"
        run: |
          PRIVATE_KEY=$(terraform -chdir=$TERRAFORM_DIR output private_key)
          PUBLIC_IPS=$(terraform -chdir=$TERRAFORM_DIR output --json public_ips)

          echo "PRIVATE_KEY<<EOF" >> $GITHUB_ENV
          echo "$PRIVATE_KEY" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          
          echo "PUBLIC_IPS<<EOF" >> $GITHUB_ENV
          echo "$PUBLIC_IPS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

  build:
    name: Build and push image (${{ matrix.PUBLIC_IP }}) # @todo Show arch in job name
    runs-on: ubuntu-latest
    needs:
      - spawn-spots
    strategy:
      matrix:
        PUBLIC_IP: ${{ fromJSON(needs.spawn-spots.outputs.PUBLIC_IPS) }}
    env:
      PUBLIC_IP: ${{ matrix.PUBLIC_IP }}
      REPOSITORY_URL: ${{ inputs.REPOSITORY_URL }}
      CHECKOUT: ${{ inputs.CHECKOUT }}
      IMAGE_NAME: ${{ inputs.DOCKER_IMAGE_NAME }}
      IMAGE_TAG: ${{ inputs.DOCKER_IMAGE_TAG }}
    steps:
      -
        name: Setup SSH client
        run: |
          mkdir -p ~/.ssh/
          echo "$PRIVATE_KEY" > ~/.ssh/private.key
          chmod 600 ~/.ssh/private.key
          cat >>~/.ssh/config <<END
          Host spot
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/private.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ubuntu
          SSH_HOST: ${{ env.PUBLIC_IP }}
          PRIVATE_KEY: ${{ needs.spawn-spots.outputs.PRIVATE_KEY }}
      -
        name: Checkout on spot instance
        run: ssh spot "mkdir ~/code && git clone \"$REPOSITORY_URL\" ~/code && cd ~/code && git checkout \"$CHECKOUT\""
      -
        name: Build docker image on spot instance
        run: ssh spot "sudo docker build -t \"$IMAGE_NAME-"'$(arch)'":$IMAGE_TAG\" ~/code"
      -
        name: Push docker image from spot instance
        run: ssh spot "sudo docker push \"$IMAGE_NAME-"'$(arch)'":$IMAGE_TAG\""

  manifest:
    name: Create and push multi-arch manifest
    runs-on: ubuntu-latest
    needs:
      - spawn-spots
      - build
    env:
      PUBLIC_IP: ${{ fromJSON(needs.spawn-spots.outputs.PUBLIC_IPS)[0] }}
      REPOSITORY_URL: ${{ inputs.REPOSITORY_URL }}
      CHECKOUT: ${{ inputs.CHECKOUT }}
      IMAGE_NAME: ${{ inputs.DOCKER_IMAGE_NAME }}
      IMAGE_TAG: ${{ inputs.DOCKER_IMAGE_TAG }}
    steps:
      -
        name: Setup SSH client
        run: |
          mkdir -p ~/.ssh/
          echo "$PRIVATE_KEY" > ~/.ssh/private.key
          chmod 600 ~/.ssh/private.key
          cat >>~/.ssh/config <<END
          Host spot
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/private.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ubuntu
          SSH_HOST: ${{ env.PUBLIC_IP }}
          PRIVATE_KEY: ${{ needs.spawn-spots.outputs.PRIVATE_KEY }}
      -
        name: Create multi-arch docker manifest
        # @todo Take x86_64 and aarch64 as variables from previous steps
        run: ssh spot "sudo docker manifest create \"$IMAGE_NAME:$IMAGE_TAG\" --amend \"$IMAGE_NAME-x86_64:$IMAGE_TAG\" --amend \"$IMAGE_NAME-aarch64:$IMAGE_TAG\""
      -
        name: Push docker manifest
        run: ssh spot "sudo docker manifest push \"$IMAGE_NAME:$IMAGE_TAG\""

  destroy-spots:
    name: Destroy spot machines
    runs-on: ubuntu-latest
    needs:
      - spawn-spots
      - build
      - manifest
    if: ${{ always() }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_docker_login: ${{ secrets.DOCKERHUB_USERNAME }}
      TF_VAR_docker_password: ${{ secrets.DOCKERHUB_TOKEN }}
      TF_VAR_aws_ec2_key_pair_name: ${{ github.repository }}@${{ github.sha }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@master
        with:
          repository: ${{ inputs.WORKFLOW_REPOSITORY }}
          ref: ${{ inputs.WORKFLOW_CHECKOUT }}
      -
        name: "Download Terraform State File"
        uses: actions/download-artifact@v2
        with:
          name: terraform-state
          path: ${{ env.TERRAFORM_DIR }}
      -
        name: "Terraform: Setup"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.5
          terraform_wrapper: false
      -
        name: "Terraform: Init"
        run: terraform -chdir=$TERRAFORM_DIR init
      -
        name: "Terraform: Destroy"
        run: terraform -chdir=$TERRAFORM_DIR destroy -auto-approve
